#!/usr/bin/env ruby

require_relative 'lib/teuton-server'

TeutonServer.show_help if ARGV.first == 'help'
TeutonServer.show_version if ARGV.first == 'version'
TeutonServer.init(ARGV) if ARGV.first == 'init'
TeutonServer.start(ARGV) if ARGV.size == 1
TeutonServer.show_help
