#!/usr/bin/env ruby

require_relative 'lib/teuton-client'

TeutonClient.show_help if ARGV.first == 'help'
TeutonClient.show_version if ARGV.first == 'version'
TeutonClient.init if ARGV.first == 'init'
TeutonClient.run(ARGV)
