# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "teuton-client" do |i|
    i.vm.box = "generic/debian9"
    i.vm.hostname = "teuton-client"
    i.vm.network "public_network", bridge: [
      "wlp1s0",
      "enp2s0"
    ]

    i.vm.provision "shell", inline: <<-SHELL
    apt-get install -y ruby
    gem install rake
    cd /opt
    git clone https://github.com/dvarrui/teuton-server.git
    cd teuton-server
    rake install_gems
    SHELL
    i.vm.provider "virtualbox" do |v|
      v.name = 'teuton-client'
      v.memory = 2048
    end
  end
end
