# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "teuton-server" do |i|
    i.vm.box = "generic/opensuse15"
    i.vm.hostname = "teuton-server"
    i.vm.network "public_network", bridge: [
      "wlp1s0",
      "enp2s0",
    ]

    i.vm.provision "shell", inline: <<-SHELL
    wget -qO- https://raw.githubusercontent.com/dvarrui/teuton/master/bin/linux_t-node_install.sh | bash
    gem install teuton-server
  SHELL
    i.vm.provider "virtualbox" do |v|
      v.name = 'teuton-server'
      v.memory = 2048
    end
  end
end
